### ISSUE TITLE
catalogo-minc: Roadmap

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#20]
# 0.x

* [ ] CRUD de projetos
* [ ] Estudos de interface

# Futuro
* [ ] Dataviz?
* [ ] QA para os softwares do catálogo?
* [ ] Direcionar comunidades
* [ ] Checklist automático?

# Estratégia de governaça
* Equipe
* Prospecção de usuários nos Ministérios e Municípios
* Identificação de necessidades da comunidade e elaboração de estratégias para atendê-las
* Instrumentalizar os softwares divulgáveis/interesse externo ao MinC
* MVP do catálogo de softwares do MinC

**Comment by joenio** [comment]
copiado de lappis-unb/catalogo-minc#1

**Comment by joenio** [comment]
o projeto do catálogo está suspenso por hora.
