### ISSUE TITLE
versalic-bi: Roadmap

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#21]
# 1.0
* [ ] Refatorar a API do Salic (salic-api)
* [ ] Redesign e usabilidade do frontend
* [ ] Dados agregados + dataviz
* [ ] Estudos de indicadores culturais (metabase ou similares)
* [ ] ML aplicado a inferências automáticas

# Futuro
* [ ] Página personalizada por projeto + QR code?
* [ ] Crowdfunding?
* [ ] Tinder cultural?

**Comment by joenio** [comment]
copiado de lappis-unb/versalic-bi#1

**Comment by joenio** [comment]
o planejamento do versalic (hoje chamado de PromovaCultura) está sendo elaborado em https://github.com/lappis-unb/PromovaCultura
