### ISSUE TITLE
salicml: Roadmap

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#22]
# 0.x
* [ ] Refatorar api do salic (salic-api)
* [ ] Minerar/entender o banco
* [ ]  Treinamento de ferramentas NLP em português/SALICquês
* [ ] Extração de features
* [ ] Classicar enquadramento de projetos 
* [ ] Deteção de anomalias/admissibilidade
* [ ] Verificação e validação dos modelos

# 1.0
* [ ] API para ser consumida pelo SALIC
* [ ] Integrar inteligência às telas de submissão do SALIC

**Comment by joenio** [comment]
copiado de lappis-unb/salicml#1

**Comment by joenio** [comment]
o planejamento da frente salic-ml está ocorrendo em contato diretamente com o minc em reuniões presenciais entre a equipe do salic-ml, veja a ata da última reunião em https://github.com/lappis-unb/EcossistemasSWLivre/wiki/Reuniao-27-03-2018-SALICML-MINC
