### ISSUE TITLE
rouana-bot: Roadmap

### ISSUE THREAD

**Issue by joenio** [lappis-unb/EcossistemasSWLivre#23]
# 1.0
* [ ] Integrar Rasa ao rocketchat
* [ ] Definir arquitetura do bot
  - Base de conhecimento e personalidade
  - Português
  - Histórias
  - Pipeline
* [ ]  Testes A/B no portal

# 2.0
* [ ] Ferramenta GUI para popular a base de dados do Bot
* [ ] Configurar bot multi-contexto
* [ ] Bot SALIC para as telas de submissão

**Comment by joenio** [comment]
copiado de lappis-unb/rouana-bot#1
